/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FilterOptions {
  'category' : [] | [ProductCategory],
  'brand' : [] | [string],
  'supermarket' : [] | [Supermarket],
}
export interface FolderOffer {
  'id' : bigint,
  'offerType' : OfferType,
  'originalPrice' : number,
  'validFrom' : Time,
  'valid' : boolean,
  'productName' : string,
  'imageUrl' : string,
  'category' : ProductCategory,
  'brand' : [] | [string],
  'supermarket' : Supermarket,
  'validUntil' : Time,
}
export interface Match {
  'createdAt' : Time,
  'user1' : Principal,
  'user2' : Principal,
  'offerId' : bigint,
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : Time,
  'user' : Principal,
  'isRead' : boolean,
}
export type NotificationType = {
    'productMatch' : { 'matchedUser' : Principal, 'offerId' : bigint }
  };
export type OfferType = { 'onePlusOneFree' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'debitCard' : null };
export type ProductCategory = { 'vlees' : null } |
  { 'bakkerij' : null } |
  { 'zuivel' : null } |
  { 'snacks' : null } |
  { 'overig' : null } |
  { 'groentenFruit' : null } |
  { 'dranken' : null };
export interface Review {
  'comment' : [] | [string],
  'timestamp' : Time,
  'rating' : bigint,
  'reviewer' : Principal,
  'sharedPaymentId' : bigint,
}
export interface SelectedProductDetail {
  'matchedUsers' : Array<Principal>,
  'product' : FolderOffer,
}
export interface SharedPayment {
  'paymentMethod' : PaymentMethod,
  'initiator' : Principal,
  'invitationId' : bigint,
  'completed' : boolean,
  'participant' : Principal,
  'offerId' : bigint,
  'amount' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Supermarket = { 'dekamarkt' : null } |
  { 'aldi' : null } |
  { 'deen' : null } |
  { 'dirk' : null } |
  { 'lidl' : null } |
  { 'spar' : null } |
  { 'jumbo' : null } |
  { 'albertHeijn' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserLocation { 'latitude' : number, 'longitude' : number }
export interface UserProductOverview {
  'sharedProducts' : Array<SelectedProductDetail>,
  'onlyCurrentUser' : Array<SelectedProductDetail>,
}
export interface UserProfile {
  'nearestSupermarket' : [] | [Supermarket],
  'birthDate' : [] | [Time],
  'preferredCategories' : Array<ProductCategory>,
  'city' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'email' : string,
  'meetingSupermarket' : [] | [Supermarket],
  'timestamp' : Time,
  'preferredSupermarkets' : Array<Supermarket>,
  'location' : [] | [UserLocation],
}
export interface UserReviews {
  'reviews' : Array<Review>,
  'averageRating' : number,
  'reviewCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFavoriteOffer' : ActorMethod<[bigint], undefined>,
  'addMultipleFavoriteOffers' : ActorMethod<[Array<bigint>], undefined>,
  'addUserSelectedProducts' : ActorMethod<[Array<bigint>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createSharedPaymentInvitation' : ActorMethod<
    [Principal, bigint, number, PaymentMethod],
    bigint
  >,
  'fetchOffersFromAlbertHeijn' : ActorMethod<[], undefined>,
  'fetchOffersFromJumbo' : ActorMethod<[], undefined>,
  'fetchOffersFromLidl' : ActorMethod<[], undefined>,
  'getAllOffersWithFilters' : ActorMethod<[FilterOptions], Array<FolderOffer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteOfferIds' : ActorMethod<[], Array<bigint>>,
  'getFavoriteOffers' : ActorMethod<[], Array<FolderOffer>>,
  'getOffers' : ActorMethod<[FilterOptions], Array<FolderOffer>>,
  'getProductMatches' : ActorMethod<[Principal], Array<Match>>,
  'getProductMatchesForUser' : ActorMethod<[Principal], Array<Match>>,
  'getSharedOfferPayments' : ActorMethod<[Principal], Array<SharedPayment>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTestLink' : ActorMethod<[], string>,
  'getUserFavorites' : ActorMethod<[Principal], Array<FolderOffer>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProductOverview' : ActorMethod<[Principal], UserProductOverview>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReviews' : ActorMethod<[Principal], UserReviews>,
  'getUserSelectedProducts' : ActorMethod<[Principal], Array<FolderOffer>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isVersion61Active' : ActorMethod<[], boolean>,
  'leaveReview' : ActorMethod<
    [Principal, bigint, bigint, [] | [string]],
    undefined
  >,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'removeFavoriteOffer' : ActorMethod<[bigint], undefined>,
  'removeProfilePhoto' : ActorMethod<[], undefined>,
  'respondToPaymentInvitation' : ActorMethod<[bigint, boolean], undefined>,
  'restart' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchOffers' : ActorMethod<[string], Array<FolderOffer>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];