/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'debitCard' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'vlees' : IDL.Null,
  'bakkerij' : IDL.Null,
  'zuivel' : IDL.Null,
  'snacks' : IDL.Null,
  'overig' : IDL.Null,
  'groentenFruit' : IDL.Null,
  'dranken' : IDL.Null,
});
export const Supermarket = IDL.Variant({
  'dekamarkt' : IDL.Null,
  'aldi' : IDL.Null,
  'deen' : IDL.Null,
  'dirk' : IDL.Null,
  'lidl' : IDL.Null,
  'spar' : IDL.Null,
  'jumbo' : IDL.Null,
  'albertHeijn' : IDL.Null,
});
export const FilterOptions = IDL.Record({
  'category' : IDL.Opt(ProductCategory),
  'brand' : IDL.Opt(IDL.Text),
  'supermarket' : IDL.Opt(Supermarket),
});
export const OfferType = IDL.Variant({ 'onePlusOneFree' : IDL.Null });
export const Time = IDL.Int;
export const FolderOffer = IDL.Record({
  'id' : IDL.Nat,
  'offerType' : OfferType,
  'originalPrice' : IDL.Float64,
  'validFrom' : Time,
  'valid' : IDL.Bool,
  'productName' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'brand' : IDL.Opt(IDL.Text),
  'supermarket' : Supermarket,
  'validUntil' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'nearestSupermarket' : IDL.Opt(Supermarket),
  'birthDate' : IDL.Opt(Time),
  'preferredCategories' : IDL.Vec(ProductCategory),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'meetingSupermarket' : IDL.Opt(Supermarket),
  'timestamp' : Time,
  'preferredSupermarkets' : IDL.Vec(Supermarket),
  'location' : IDL.Opt(UserLocation),
});
export const Match = IDL.Record({
  'createdAt' : Time,
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
  'offerId' : IDL.Nat,
});
export const SharedPayment = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'initiator' : IDL.Principal,
  'invitationId' : IDL.Nat,
  'completed' : IDL.Bool,
  'participant' : IDL.Principal,
  'offerId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const NotificationType = IDL.Variant({
  'productMatch' : IDL.Record({
    'matchedUser' : IDL.Principal,
    'offerId' : IDL.Nat,
  }),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
});
export const SelectedProductDetail = IDL.Record({
  'matchedUsers' : IDL.Vec(IDL.Principal),
  'product' : FolderOffer,
});
export const UserProductOverview = IDL.Record({
  'sharedProducts' : IDL.Vec(SelectedProductDetail),
  'onlyCurrentUser' : IDL.Vec(SelectedProductDetail),
});
export const Review = IDL.Record({
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
  'sharedPaymentId' : IDL.Nat,
});
export const UserReviews = IDL.Record({
  'reviews' : IDL.Vec(Review),
  'averageRating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFavoriteOffer' : IDL.Func([IDL.Nat], [], []),
  'addMultipleFavoriteOffers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'addUserSelectedProducts' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSharedPaymentInvitation' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Float64, PaymentMethod],
      [IDL.Nat],
      [],
    ),
  'fetchOffersFromAlbertHeijn' : IDL.Func([], [], []),
  'fetchOffersFromJumbo' : IDL.Func([], [], []),
  'fetchOffersFromLidl' : IDL.Func([], [], []),
  'getAllOffersWithFilters' : IDL.Func(
      [FilterOptions],
      [IDL.Vec(FolderOffer)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteOfferIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getFavoriteOffers' : IDL.Func([], [IDL.Vec(FolderOffer)], ['query']),
  'getOffers' : IDL.Func([FilterOptions], [IDL.Vec(FolderOffer)], ['query']),
  'getProductMatches' : IDL.Func([IDL.Principal], [IDL.Vec(Match)], ['query']),
  'getProductMatchesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Match)],
      ['query'],
    ),
  'getSharedOfferPayments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SharedPayment)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTestLink' : IDL.Func([], [IDL.Text], ['query']),
  'getUserFavorites' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FolderOffer)],
      ['query'],
    ),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProductOverview' : IDL.Func(
      [IDL.Principal],
      [UserProductOverview],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReviews' : IDL.Func([IDL.Principal], [UserReviews], ['query']),
  'getUserSelectedProducts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FolderOffer)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isVersion61Active' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveReview' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'removeFavoriteOffer' : IDL.Func([IDL.Nat], [], []),
  'removeProfilePhoto' : IDL.Func([], [], []),
  'respondToPaymentInvitation' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'restart' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchOffers' : IDL.Func([IDL.Text], [IDL.Vec(FolderOffer)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'debitCard' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'vlees' : IDL.Null,
    'bakkerij' : IDL.Null,
    'zuivel' : IDL.Null,
    'snacks' : IDL.Null,
    'overig' : IDL.Null,
    'groentenFruit' : IDL.Null,
    'dranken' : IDL.Null,
  });
  const Supermarket = IDL.Variant({
    'dekamarkt' : IDL.Null,
    'aldi' : IDL.Null,
    'deen' : IDL.Null,
    'dirk' : IDL.Null,
    'lidl' : IDL.Null,
    'spar' : IDL.Null,
    'jumbo' : IDL.Null,
    'albertHeijn' : IDL.Null,
  });
  const FilterOptions = IDL.Record({
    'category' : IDL.Opt(ProductCategory),
    'brand' : IDL.Opt(IDL.Text),
    'supermarket' : IDL.Opt(Supermarket),
  });
  const OfferType = IDL.Variant({ 'onePlusOneFree' : IDL.Null });
  const Time = IDL.Int;
  const FolderOffer = IDL.Record({
    'id' : IDL.Nat,
    'offerType' : OfferType,
    'originalPrice' : IDL.Float64,
    'validFrom' : Time,
    'valid' : IDL.Bool,
    'productName' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'brand' : IDL.Opt(IDL.Text),
    'supermarket' : Supermarket,
    'validUntil' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'nearestSupermarket' : IDL.Opt(Supermarket),
    'birthDate' : IDL.Opt(Time),
    'preferredCategories' : IDL.Vec(ProductCategory),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'meetingSupermarket' : IDL.Opt(Supermarket),
    'timestamp' : Time,
    'preferredSupermarkets' : IDL.Vec(Supermarket),
    'location' : IDL.Opt(UserLocation),
  });
  const Match = IDL.Record({
    'createdAt' : Time,
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
    'offerId' : IDL.Nat,
  });
  const SharedPayment = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'initiator' : IDL.Principal,
    'invitationId' : IDL.Nat,
    'completed' : IDL.Bool,
    'participant' : IDL.Principal,
    'offerId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const NotificationType = IDL.Variant({
    'productMatch' : IDL.Record({
      'matchedUser' : IDL.Principal,
      'offerId' : IDL.Nat,
    }),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
  });
  const SelectedProductDetail = IDL.Record({
    'matchedUsers' : IDL.Vec(IDL.Principal),
    'product' : FolderOffer,
  });
  const UserProductOverview = IDL.Record({
    'sharedProducts' : IDL.Vec(SelectedProductDetail),
    'onlyCurrentUser' : IDL.Vec(SelectedProductDetail),
  });
  const Review = IDL.Record({
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
    'sharedPaymentId' : IDL.Nat,
  });
  const UserReviews = IDL.Record({
    'reviews' : IDL.Vec(Review),
    'averageRating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFavoriteOffer' : IDL.Func([IDL.Nat], [], []),
    'addMultipleFavoriteOffers' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'addUserSelectedProducts' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSharedPaymentInvitation' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Float64, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'fetchOffersFromAlbertHeijn' : IDL.Func([], [], []),
    'fetchOffersFromJumbo' : IDL.Func([], [], []),
    'fetchOffersFromLidl' : IDL.Func([], [], []),
    'getAllOffersWithFilters' : IDL.Func(
        [FilterOptions],
        [IDL.Vec(FolderOffer)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteOfferIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getFavoriteOffers' : IDL.Func([], [IDL.Vec(FolderOffer)], ['query']),
    'getOffers' : IDL.Func([FilterOptions], [IDL.Vec(FolderOffer)], ['query']),
    'getProductMatches' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'getProductMatchesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'getSharedOfferPayments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SharedPayment)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTestLink' : IDL.Func([], [IDL.Text], ['query']),
    'getUserFavorites' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FolderOffer)],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProductOverview' : IDL.Func(
        [IDL.Principal],
        [UserProductOverview],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReviews' : IDL.Func([IDL.Principal], [UserReviews], ['query']),
    'getUserSelectedProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FolderOffer)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isVersion61Active' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveReview' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'removeFavoriteOffer' : IDL.Func([IDL.Nat], [], []),
    'removeProfilePhoto' : IDL.Func([], [], []),
    'respondToPaymentInvitation' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'restart' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchOffers' : IDL.Func([IDL.Text], [IDL.Vec(FolderOffer)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };