/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FolderOffer {
    id: bigint;
    offerType: OfferType;
    originalPrice: number;
    validFrom: Time;
    valid: boolean;
    productName: string;
    imageUrl: string;
    category: ProductCategory;
    brand?: string;
    supermarket: Supermarket;
    validUntil: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FilterOptions {
    category?: ProductCategory;
    brand?: string;
    supermarket?: Supermarket;
}
export interface UserLocation {
    latitude: number;
    longitude: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Review {
    comment?: string;
    timestamp: Time;
    rating: bigint;
    reviewer: Principal;
    sharedPaymentId: bigint;
}
export interface UserProductOverview {
    sharedProducts: Array<SelectedProductDetail>;
    onlyCurrentUser: Array<SelectedProductDetail>;
}
export interface SelectedProductDetail {
    matchedUsers: Array<Principal>;
    product: FolderOffer;
}
export interface UserReviews {
    reviews: Array<Review>;
    averageRating: number;
    reviewCount: bigint;
}
export interface Match {
    createdAt: Time;
    user1: Principal;
    user2: Principal;
    offerId: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type NotificationType = {
    __kind__: "productMatch";
    productMatch: {
        matchedUser: Principal;
        offerId: bigint;
    };
};
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Notification {
    id: bigint;
    notificationType: NotificationType;
    createdAt: Time;
    user: Principal;
    isRead: boolean;
}
export interface SharedPayment {
    paymentMethod: PaymentMethod;
    initiator: Principal;
    invitationId: bigint;
    completed: boolean;
    participant: Principal;
    offerId: bigint;
    amount: number;
}
export interface UserProfile {
    nearestSupermarket?: Supermarket;
    birthDate?: Time;
    preferredCategories: Array<ProductCategory>;
    city: string;
    name: string;
    profilePhoto?: ExternalBlob;
    email: string;
    meetingSupermarket?: Supermarket;
    timestamp: Time;
    preferredSupermarkets: Array<Supermarket>;
    location?: UserLocation;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OfferType {
    onePlusOneFree = "onePlusOneFree"
}
export enum PaymentMethod {
    cash = "cash",
    debitCard = "debitCard"
}
export enum ProductCategory {
    vlees = "vlees",
    bakkerij = "bakkerij",
    zuivel = "zuivel",
    snacks = "snacks",
    overig = "overig",
    groentenFruit = "groentenFruit",
    dranken = "dranken"
}
export enum Supermarket {
    dekamarkt = "dekamarkt",
    aldi = "aldi",
    deen = "deen",
    dirk = "dirk",
    lidl = "lidl",
    spar = "spar",
    jumbo = "jumbo",
    albertHeijn = "albertHeijn"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addFavoriteOffer(offerId: bigint): Promise<void>;
    addMultipleFavoriteOffers(offerIds: Array<bigint>): Promise<void>;
    addUserSelectedProducts(productIds: Array<bigint>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createSharedPaymentInvitation(participant: Principal, offerId: bigint, amount: number, paymentMethod: PaymentMethod): Promise<bigint>;
    fetchOffersFromAlbertHeijn(): Promise<void>;
    fetchOffersFromJumbo(): Promise<void>;
    fetchOffersFromLidl(): Promise<void>;
    getAllOffersWithFilters(_filters: FilterOptions): Promise<Array<FolderOffer>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavoriteOfferIds(): Promise<Array<bigint>>;
    getFavoriteOffers(): Promise<Array<FolderOffer>>;
    getOffers(_filters: FilterOptions): Promise<Array<FolderOffer>>;
    getProductMatches(user: Principal): Promise<Array<Match>>;
    getProductMatchesForUser(user: Principal): Promise<Array<Match>>;
    getSharedOfferPayments(user: Principal): Promise<Array<SharedPayment>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTestLink(): Promise<string>;
    getUserFavorites(user: Principal): Promise<Array<FolderOffer>>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProductOverview(user: Principal): Promise<UserProductOverview>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserReviews(user: Principal): Promise<UserReviews>;
    getUserSelectedProducts(user: Principal): Promise<Array<FolderOffer>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isVersion61Active(): Promise<boolean>;
    leaveReview(toUser: Principal, sharedPaymentId: bigint, rating: bigint, comment: string | null): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    removeFavoriteOffer(offerId: bigint): Promise<void>;
    removeProfilePhoto(): Promise<void>;
    respondToPaymentInvitation(invitationId: bigint, accept: boolean): Promise<void>;
    restart(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchOffers(_searchText: string): Promise<Array<FolderOffer>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    uploadProfilePhoto(photo: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, FilterOptions as _FilterOptions, FolderOffer as _FolderOffer, Notification as _Notification, NotificationType as _NotificationType, OfferType as _OfferType, PaymentMethod as _PaymentMethod, ProductCategory as _ProductCategory, Review as _Review, SelectedProductDetail as _SelectedProductDetail, SharedPayment as _SharedPayment, StripeSessionStatus as _StripeSessionStatus, Supermarket as _Supermarket, Time as _Time, UserLocation as _UserLocation, UserProductOverview as _UserProductOverview, UserProfile as _UserProfile, UserReviews as _UserReviews, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addFavoriteOffer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteOffer(arg0);
            return result;
        }
    }
    async addMultipleFavoriteOffers(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMultipleFavoriteOffers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMultipleFavoriteOffers(arg0);
            return result;
        }
    }
    async addUserSelectedProducts(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserSelectedProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserSelectedProducts(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createSharedPaymentInvitation(arg0: Principal, arg1: bigint, arg2: number, arg3: PaymentMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSharedPaymentInvitation(arg0, arg1, arg2, to_candid_PaymentMethod_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSharedPaymentInvitation(arg0, arg1, arg2, to_candid_PaymentMethod_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async fetchOffersFromAlbertHeijn(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchOffersFromAlbertHeijn();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchOffersFromAlbertHeijn();
            return result;
        }
    }
    async fetchOffersFromJumbo(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchOffersFromJumbo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchOffersFromJumbo();
            return result;
        }
    }
    async fetchOffersFromLidl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchOffersFromLidl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchOffersFromLidl();
            return result;
        }
    }
    async getAllOffersWithFilters(arg0: FilterOptions): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffersWithFilters(to_candid_FilterOptions_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffersWithFilters(to_candid_FilterOptions_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavoriteOfferIds(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteOfferIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteOfferIds();
            return result;
        }
    }
    async getFavoriteOffers(): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteOffers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteOffers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffers(arg0: FilterOptions): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffers(to_candid_FilterOptions_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffers(to_candid_FilterOptions_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductMatches(arg0: Principal): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductMatches(arg0);
            return result;
        }
    }
    async getProductMatchesForUser(arg0: Principal): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductMatchesForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductMatchesForUser(arg0);
            return result;
        }
    }
    async getSharedOfferPayments(arg0: Principal): Promise<Array<SharedPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedOfferPayments(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedOfferPayments(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestLink(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestLink();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestLink();
            return result;
        }
    }
    async getUserFavorites(arg0: Principal): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFavorites(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFavorites(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProductOverview(arg0: Principal): Promise<UserProductOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProductOverview(arg0);
                return from_candid_UserProductOverview_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProductOverview(arg0);
            return from_candid_UserProductOverview_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserReviews(arg0: Principal): Promise<UserReviews> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserReviews(arg0);
                return from_candid_UserReviews_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserReviews(arg0);
            return from_candid_UserReviews_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSelectedProducts(arg0: Principal): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSelectedProducts(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSelectedProducts(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isVersion61Active(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVersion61Active();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVersion61Active();
            return result;
        }
    }
    async leaveReview(arg0: Principal, arg1: bigint, arg2: bigint, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveReview(arg0, arg1, arg2, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveReview(arg0, arg1, arg2, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async removeFavoriteOffer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteOffer(arg0);
            return result;
        }
    }
    async removeProfilePhoto(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfilePhoto();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfilePhoto();
            return result;
        }
    }
    async respondToPaymentInvitation(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToPaymentInvitation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToPaymentInvitation(arg0, arg1);
            return result;
        }
    }
    async restart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restart();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchOffers(arg0: string): Promise<Array<FolderOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchOffers(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchOffers(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async uploadProfilePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FolderOffer_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FolderOffer): FolderOffer {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_OfferType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferType): OfferType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_SelectedProductDetail_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SelectedProductDetail): SelectedProductDetail {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SharedPayment_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedPayment): SharedPayment {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Supermarket_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Supermarket): Supermarket {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProductOverview_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProductOverview): UserProductOverview {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserReviews_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserReviews): UserReviews {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Supermarket]): Supermarket | null {
    return value.length === 0 ? null : from_candid_Supermarket_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserLocation]): UserLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    offerType: _OfferType;
    originalPrice: number;
    validFrom: _Time;
    valid: boolean;
    productName: string;
    imageUrl: string;
    category: _ProductCategory;
    brand: [] | [string];
    supermarket: _Supermarket;
    validUntil: _Time;
}): {
    id: bigint;
    offerType: OfferType;
    originalPrice: number;
    validFrom: Time;
    valid: boolean;
    productName: string;
    imageUrl: string;
    category: ProductCategory;
    brand?: string;
    supermarket: Supermarket;
    validUntil: Time;
} {
    return {
        id: value.id,
        offerType: from_candid_OfferType_n21(_uploadFile, _downloadFile, value.offerType),
        originalPrice: value.originalPrice,
        validFrom: value.validFrom,
        valid: value.valid,
        productName: value.productName,
        imageUrl: value.imageUrl,
        category: from_candid_ProductCategory_n23(_uploadFile, _downloadFile, value.category),
        brand: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.brand)),
        supermarket: from_candid_Supermarket_n26(_uploadFile, _downloadFile, value.supermarket),
        validUntil: value.validUntil
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nearestSupermarket: [] | [_Supermarket];
    birthDate: [] | [_Time];
    preferredCategories: Array<_ProductCategory>;
    city: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    email: string;
    meetingSupermarket: [] | [_Supermarket];
    timestamp: _Time;
    preferredSupermarkets: Array<_Supermarket>;
    location: [] | [_UserLocation];
}): Promise<{
    nearestSupermarket?: Supermarket;
    birthDate?: Time;
    preferredCategories: Array<ProductCategory>;
    city: string;
    name: string;
    profilePhoto?: ExternalBlob;
    email: string;
    meetingSupermarket?: Supermarket;
    timestamp: Time;
    preferredSupermarkets: Array<Supermarket>;
    location?: UserLocation;
}> {
    return {
        nearestSupermarket: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.nearestSupermarket)),
        birthDate: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.birthDate)),
        preferredCategories: from_candid_vec_n33(_uploadFile, _downloadFile, value.preferredCategories),
        city: value.city,
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.profilePhoto)),
        email: value.email,
        meetingSupermarket: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.meetingSupermarket)),
        timestamp: value.timestamp,
        preferredSupermarkets: from_candid_vec_n36(_uploadFile, _downloadFile, value.preferredSupermarkets),
        location: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: _PaymentMethod;
    initiator: Principal;
    invitationId: bigint;
    completed: boolean;
    participant: Principal;
    offerId: bigint;
    amount: number;
}): {
    paymentMethod: PaymentMethod;
    initiator: Principal;
    invitationId: bigint;
    completed: boolean;
    participant: Principal;
    offerId: bigint;
    amount: number;
} {
    return {
        paymentMethod: from_candid_PaymentMethod_n43(_uploadFile, _downloadFile, value.paymentMethod),
        initiator: value.initiator,
        invitationId: value.invitationId,
        completed: value.completed,
        participant: value.participant,
        offerId: value.offerId,
        amount: value.amount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notificationType: _NotificationType;
    createdAt: _Time;
    user: Principal;
    isRead: boolean;
}): {
    id: bigint;
    notificationType: NotificationType;
    createdAt: Time;
    user: Principal;
    isRead: boolean;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n51(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        user: value.user,
        isRead: value.isRead
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sharedProducts: Array<_SelectedProductDetail>;
    onlyCurrentUser: Array<_SelectedProductDetail>;
}): {
    sharedProducts: Array<SelectedProductDetail>;
    onlyCurrentUser: Array<SelectedProductDetail>;
} {
    return {
        sharedProducts: from_candid_vec_n55(_uploadFile, _downloadFile, value.sharedProducts),
        onlyCurrentUser: from_candid_vec_n55(_uploadFile, _downloadFile, value.onlyCurrentUser)
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchedUsers: Array<Principal>;
    product: _FolderOffer;
}): {
    matchedUsers: Array<Principal>;
    product: FolderOffer;
} {
    return {
        matchedUsers: value.matchedUsers,
        product: from_candid_FolderOffer_n19(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reviews: Array<_Review>;
    averageRating: number;
    reviewCount: bigint;
}): {
    reviews: Array<Review>;
    averageRating: number;
    reviewCount: bigint;
} {
    return {
        reviews: from_candid_vec_n60(_uploadFile, _downloadFile, value.reviews),
        averageRating: value.averageRating,
        reviewCount: value.reviewCount
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comment: [] | [string];
    timestamp: _Time;
    rating: bigint;
    reviewer: Principal;
    sharedPaymentId: bigint;
}): {
    comment?: string;
    timestamp: Time;
    rating: bigint;
    reviewer: Principal;
    sharedPaymentId: bigint;
} {
    return {
        comment: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.comment)),
        timestamp: value.timestamp,
        rating: value.rating,
        reviewer: value.reviewer,
        sharedPaymentId: value.sharedPaymentId
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onePlusOneFree: null;
}): OfferType {
    return "onePlusOneFree" in value ? OfferType.onePlusOneFree : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vlees: null;
} | {
    bakkerij: null;
} | {
    zuivel: null;
} | {
    snacks: null;
} | {
    overig: null;
} | {
    groentenFruit: null;
} | {
    dranken: null;
}): ProductCategory {
    return "vlees" in value ? ProductCategory.vlees : "bakkerij" in value ? ProductCategory.bakkerij : "zuivel" in value ? ProductCategory.zuivel : "snacks" in value ? ProductCategory.snacks : "overig" in value ? ProductCategory.overig : "groentenFruit" in value ? ProductCategory.groentenFruit : "dranken" in value ? ProductCategory.dranken : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dekamarkt: null;
} | {
    aldi: null;
} | {
    deen: null;
} | {
    dirk: null;
} | {
    lidl: null;
} | {
    spar: null;
} | {
    jumbo: null;
} | {
    albertHeijn: null;
}): Supermarket {
    return "dekamarkt" in value ? Supermarket.dekamarkt : "aldi" in value ? Supermarket.aldi : "deen" in value ? Supermarket.deen : "dirk" in value ? Supermarket.dirk : "lidl" in value ? Supermarket.lidl : "spar" in value ? Supermarket.spar : "jumbo" in value ? Supermarket.jumbo : "albertHeijn" in value ? Supermarket.albertHeijn : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    debitCard: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "debitCard" in value ? PaymentMethod.debitCard : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n47(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productMatch: {
        matchedUser: Principal;
        offerId: bigint;
    };
}): {
    __kind__: "productMatch";
    productMatch: {
        matchedUser: Principal;
        offerId: bigint;
    };
} {
    return "productMatch" in value ? {
        __kind__: "productMatch",
        productMatch: value.productMatch
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FolderOffer>): Array<FolderOffer> {
    return value.map((x)=>from_candid_FolderOffer_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductCategory>): Array<ProductCategory> {
    return value.map((x)=>from_candid_ProductCategory_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Supermarket>): Array<Supermarket> {
    return value.map((x)=>from_candid_Supermarket_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SharedPayment>): Array<SharedPayment> {
    return value.map((x)=>from_candid_SharedPayment_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SelectedProductDetail>): Array<SelectedProductDetail> {
    return value.map((x)=>from_candid_SelectedProductDetail_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n61(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FilterOptions_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilterOptions): _FilterOptions {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Supermarket_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Supermarket): _Supermarket {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category?: ProductCategory;
    brand?: string;
    supermarket?: Supermarket;
}): {
    category: [] | [_ProductCategory];
    brand: [] | [string];
    supermarket: [] | [_Supermarket];
} {
    return {
        category: value.category ? candid_some(to_candid_ProductCategory_n14(_uploadFile, _downloadFile, value.category)) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        supermarket: value.supermarket ? candid_some(to_candid_Supermarket_n16(_uploadFile, _downloadFile, value.supermarket)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nearestSupermarket?: Supermarket;
    birthDate?: Time;
    preferredCategories: Array<ProductCategory>;
    city: string;
    name: string;
    profilePhoto?: ExternalBlob;
    email: string;
    meetingSupermarket?: Supermarket;
    timestamp: Time;
    preferredSupermarkets: Array<Supermarket>;
    location?: UserLocation;
}): Promise<{
    nearestSupermarket: [] | [_Supermarket];
    birthDate: [] | [_Time];
    preferredCategories: Array<_ProductCategory>;
    city: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    email: string;
    meetingSupermarket: [] | [_Supermarket];
    timestamp: _Time;
    preferredSupermarkets: Array<_Supermarket>;
    location: [] | [_UserLocation];
}> {
    return {
        nearestSupermarket: value.nearestSupermarket ? candid_some(to_candid_Supermarket_n16(_uploadFile, _downloadFile, value.nearestSupermarket)) : candid_none(),
        birthDate: value.birthDate ? candid_some(value.birthDate) : candid_none(),
        preferredCategories: to_candid_vec_n66(_uploadFile, _downloadFile, value.preferredCategories),
        city: value.city,
        name: value.name,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n67(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        email: value.email,
        meetingSupermarket: value.meetingSupermarket ? candid_some(to_candid_Supermarket_n16(_uploadFile, _downloadFile, value.meetingSupermarket)) : candid_none(),
        timestamp: value.timestamp,
        preferredSupermarkets: to_candid_vec_n68(_uploadFile, _downloadFile, value.preferredSupermarkets),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    debitCard: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.debitCard ? {
        debitCard: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    vlees: null;
} | {
    bakkerij: null;
} | {
    zuivel: null;
} | {
    snacks: null;
} | {
    overig: null;
} | {
    groentenFruit: null;
} | {
    dranken: null;
} {
    return value == ProductCategory.vlees ? {
        vlees: null
    } : value == ProductCategory.bakkerij ? {
        bakkerij: null
    } : value == ProductCategory.zuivel ? {
        zuivel: null
    } : value == ProductCategory.snacks ? {
        snacks: null
    } : value == ProductCategory.overig ? {
        overig: null
    } : value == ProductCategory.groentenFruit ? {
        groentenFruit: null
    } : value == ProductCategory.dranken ? {
        dranken: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Supermarket): {
    dekamarkt: null;
} | {
    aldi: null;
} | {
    deen: null;
} | {
    dirk: null;
} | {
    lidl: null;
} | {
    spar: null;
} | {
    jumbo: null;
} | {
    albertHeijn: null;
} {
    return value == Supermarket.dekamarkt ? {
        dekamarkt: null
    } : value == Supermarket.aldi ? {
        aldi: null
    } : value == Supermarket.deen ? {
        deen: null
    } : value == Supermarket.dirk ? {
        dirk: null
    } : value == Supermarket.lidl ? {
        lidl: null
    } : value == Supermarket.spar ? {
        spar: null
    } : value == Supermarket.jumbo ? {
        jumbo: null
    } : value == Supermarket.albertHeijn ? {
        albertHeijn: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProductCategory>): Array<_ProductCategory> {
    return value.map((x)=>to_candid_ProductCategory_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Supermarket>): Array<_Supermarket> {
    return value.map((x)=>to_candid_Supermarket_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
